pub mod BuildImports {
    pub use {
        std::mem,
        smashline::*,    
        smashline::Priority::*,
        smashline::{
            Agent, 
            Main, 
            Pre, 
            Init, 
            Exec, 
            End, 
            Exit, 
            ExecStop, 
            CheckDamage, 
            CheckAttack, 
            MapCorrection, 
            FixCamera, 
            FixPosSlow, 
            original_status
        },   
        smash_script::{*, macros::*},
        smash::app::{*, 
            lua_bind::{*, 
                KineticEnergy, 
                KineticEnergyNormal,
                FighterCutInManager,
                FighterManager,
                FighterInformation,
                BattleObjectWorld,
                BattleObjectManager,
                AttackData,
                StageManager,
                BossManager,
                Item,
                ItemManager,
                ItemParamAccessor,
                LinkEventMask,
                LinkEventThrow,
                LinkEventStarShot,
                LinkEventCaptureFishingrodDamage,
                FighterKineticEnergyMotion,
                FighterKineticEnergyGravity,
                FighterRyuLinkEventFinalMoveTarget,
                FighterSpiritsSupportSkill,
                FighterInklingLinkEventPaint,
                GimmickEventSpring,
                GimmickEventTornadoMoveInfo,
                GimmickEventBarrel,
                GimmickEventDrumRelease,
                GimmickEventLadder
            },
            Fighter, 
            sv_information ,
            smashball::is_training_mode   
        },
        smash::phx::{Hash40, Vector2f, Vector3f, Vector4f},
        smash::{hash40},
        smash::lib::{
            L2CAgent,
            L2CValue,
            lua_const::*,
            L2CValueType::*, 
            L2CValueType, 
            L2CTable, 
            L2CTable_meta, 
            L2CInnerFunctionBase, 
            L2CValueInner
        },
        smash::lib::lua_const::EffectScreenLayer::{GROUND, CHAR},
        smash::lua2cpp::{*, L2CAgentBase, L2CFighterCommon, L2CWeaponCommon, L2CFighterBase},
        singletons::*,
        smash::app::sv_animcmd::{
            frame, 
            wait, 
            execute,
            get_value_float, 
            get_value_int,
            wait_loop, 
            stop, 
            wait_loop_sync_mot, 
            frame_clear,
            FT_START_CUTIN_arg1,
            SET_SPEED,
            CHECK_FINISH_CAMERA_IF_NOT_HP_MODE,
            SET_AIR,
        },
        skyline::{c_str, from_c_str, nn::ro::LookupSymbol},
        skyline::nro::{self, NroInfo},
        std::f32::consts::PI,
        std::f32::{INFINITY, MAX, MIN},
        smash::app::BattleObjectModuleAccessor,
        skyline::hooks::InlineCtx,
    };
}